# Generated by Django 2.0.4 on 2018-04-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very good'), (5, 'Excellent')])),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('prep_time', models.CharField(blank=True, max_length=20)),
                ('cooking_time', models.CharField(blank=True, max_length=20)),
                ('serves', models.CharField(max_length=100)),
                ('ingredients', models.TextField(max_length=1000)),
                ('cooking_instructions', models.TextField(max_length=1000)),
                ('image', models.FileField(upload_to='recipe')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
